### ISSUE TITLE
The Wire.endTransmission() is not a stop.

### ISSUE THREAD

**Issue by Koepel** [AtomicTime/Nitrogen#1]
In the file "Nitrogen/Firmware/lib/XIO/XIO.cpp" there are two extra Wire.endTransmission(): `Wire.endTransmission(true); // Make sure we send a stop bit`.
That is not how to use the Wire library. The Wire.endTransmission() is not a stop and it should not be used on its own.

The [ESP32 Wire.endTransmission()](https://github.com/espressif/arduino-esp32/blob/2a1a62a90a849a4aa172036bf79ef1097495b1a7/libraries/Wire/src/Wire.cpp#L109) calls [the function i2cWrite()](https://github.com/espressif/arduino-esp32/blob/2a1a62a90a849a4aa172036bf79ef1097495b1a7/libraries/Wire/src/Wire.cpp#L109). As you can see, that is not a stop.

For the ESP processors, the Wire.reset() is used to reset the I2C bus. The Wire.reset() is however not a standard Arduino function and is in my opinion a workaround for a bug. The ESP library should be compatible with the Arduino Wire library and the ESP library should take care of leaving the I2C bus in a normal state when an error occures.

**Comment by CT3** [comment]
Thanks for the information!
I'm using: https://github.com/stickbreaker/arduino-esp32 
And it has fixed the problem with I2C crashing. 

I will looks into using Wire.reset().

**Comment by CT3** [comment]
Lots of changes in the new rev of ESP Wire.reset() is not a valid function anymore
